### ISSUE TITLE
`runCatching` breaks coroutines' structured concurrency

### ISSUE THREAD

**Issue by Tgo1014** [monstar-lab-oss/android-template#50]
[This article](https://www.jacobras.nl/2022/04/resilient-use-cases-with-kotlin-result-coroutines-and-annotations/) came to my attention, it links [this discussion](https://github.com/Kotlin/kotlinx.coroutines/issues/1814) on `kotlinx.coroutines` repo which talks about `runCatching` breaking how coroutines are supposed to work. Apparently, Google has added a custom solution in the [Now On Android repository](https://github.com/android/nowinandroid/blob/607c24e7f7399942e278af663ea4ad350e5bbc3a/core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/SyncUtilities.kt#L57) handling this specific problem, which raises it importancy.

I recommend taking a look at the links for this discussion.

This brings forward the issue: should we handle this in our template by adding an extension that handles this and updating it with examples of usage?

Also, how should we handle this?
- Adding an extension with a similar name? (In my opinion, this can cause confusion)
- Use "resultOf" as the name like in the article, which is different enough to differentiate from the `kotlinx` one but shows its meaning?
- Another option?

I'm opening this issue so we can discuss what action to take to improve on this.

**Comment by levinzonr** [comment]
I think we def need something like this, so let's come with the name suggestions and vote 🇺🇸
